version: '3'

services:
  service:
    image: "cr_tile_game_service:latest"
    container_name: "cr_tile_game_service"
    restart: unless-stopped
    ports:
      - "8114:8114"
    volumes:
      - "./tile_service_data:/data"

  db:
    build: https://github.com/CoryRobertson/smol_db.git
    ports:
      - "8222:8222"
    container_name: "smol_db_server"
    restart: unless-stopped
    volumes:
      - "./tile_service_data/db:/data"